---
- name: Install required software
  hosts: db
  become: yes
  tasks:
    - yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - httpd
          - git
          - tcpdump
          - php
    - service:
        name: httpd
        state: started
        enabled: yes
      with_items:
        - "{{ packages }}"
